---
    
# removing from the source, requires, connecting to the destination
- name: Construct key
  set_fact:
    combined_key: "{{ svm_name + ':' + item.destination_vserver }}"

- name: Filter vserver_peer_info
  set_fact:
    selected_peer_info: "{{ sm_info.ontap_info.vserver_peer_info[combined_key] | default({}) }}"

- name: Get destination info
  set_fact:
    cluster2_info: "{{ clusters | selectattr('name', 'equalto', selected_peer_info.peer_cluster) | first }}"

- name: Correct connection info
  # we set the hostname to peer cluster, since we need to remove from the destination side
  # which we selected previously
  set_fact:
    netapp_hostname: "{{ cluster2_info.management_ip }}"


- set_fact:
    auth: &auth
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

- name: Get destination connection info
  set_fact:
    cluster2_name: "{{ cluster2_info.name }}"
    svm2_name: "{{ item.destination_vserver }}"
    volume_name: "{{ item.source_volume }}"
    volume2_name: "{{ item.destination_volume }}"

- name: Modify policy SnapMirror (bug fix) - to allow snapmirror break
  netapp.ontap.na_ontap_snapmirror:
    state: present
    policy                      : "MirrorAllSnapshots"
    source_endpoint             : 
      cluster                   : "{{ cluster_name }}"
      path                      : "{{ svm_name + ':' + volume_name }}"    
    destination_endpoint        : 
      cluster                   : "{{ cluster2_name }}"
      path                      : "{{ svm2_name + ':' + volume2_name }}"
    <<: *auth

- name: "Removing snapmirror {{ volume_name }} -/-> {{ volume2_name }}"  
  netapp.ontap.na_ontap_snapmirror:
    use_rest                    : always
    state                       : absent
    source_endpoint             : 
      cluster                   : "{{ cluster_name }}"
      path                      : "{{ svm_name + ':' + volume_name }}"    
    destination_endpoint        : 
      cluster                   : "{{ cluster2_name }}"
      path                      : "{{ svm2_name + ':' + volume2_name }}"    
    <<: *auth
  retries: 5
  delay: 60
