ontap:
  user: admin
  password: "**"
ad:
  user: administrator
  password: "**"
vcenter:
  host: jabba.slash.local
  user: administrator@vsphere.local
  password: "**"
aiqum:
  host: 172.16.0.88
  user: admin
  password: "**"