---
- name: "Day 0 Operations - Create cluster"
  hosts: "localhost"
  become: false
  gather_facts: false
  vars_files:
    - "vars/credentials.yml"
    - "vars/defaults.yml"

  roles:
    - { role: facts, qtask: credentials }  
    - { role: cluster, qtask: facts }       
    - { role: cluster, qtask: create }     
    - { role: aiqum, qtask: facts }       
    - { role: aiqum, qtask: register }     