---
- name: "Day 2 - Decommmision Nas"
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - "vars/credentials.yml"
    - "vars/defaults.yml"
    - "vars/overrides.yml"

  roles:
    - { role: facts, qtask: credentials }  
    - { role: volumes, qtask: facts }
    - { role: volumes, qtask: decom }
    - { role: aiqum, qtask: facts }
    - { role: aiqum, qtask: rediscover }      
