---
- name: "Day 1 - Create Svm"
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - "vars/credentials.yml"
    - "vars/defaults.yml"
    - "vars/overrides.yml"

  roles:
    - { role: facts, qtask: credentials }  
    - { role: svm, qtask: facts }
    - { role: svm, qtask: delete }    
    - { role: aiqum, qtask: facts }
    - { role: aiqum, qtask: rediscover }
